import { Category, Collection, Game, Platform } from '@/lib/types';

const image = (label: string, mode: 'cover' | 'banner' | 'gallery' = 'cover') => {
  const size = mode === 'banner' ? '1600x900' : mode === 'gallery' ? '1200x800' : '800x1000';
  return `https://placehold.co/${size}/0f172a/e2e8f0?text=${encodeURIComponent(label)}`;
};

export const platforms: Platform[] = [
  { id: 'p1', name: 'PC', slug: 'pc' },
  { id: 'p2', name: 'Mac', slug: 'mac' },
  { id: 'p3', name: 'Browser', slug: 'browser' },
  { id: 'p4', name: 'Android', slug: 'android' },
  { id: 'p5', name: 'iPhone / iPad', slug: 'ios' },
  { id: 'p6', name: 'Steam', slug: 'steam' },
  { id: 'p7', name: 'itch.io', slug: 'itchio' },
  { id: 'p8', name: 'GitHub', slug: 'github' }
];

export const categories: Category[] = [
  { id: 'c1', name: 'Action', slug: 'action', description: 'Fast combat, movement, and high-intensity picks.', gameCount: 12 },
  { id: 'c2', name: 'Adventure', slug: 'adventure', description: 'Explore worlds, stories, and memorable journeys.', gameCount: 9 },
  { id: 'c3', name: 'Puzzle', slug: 'puzzle', description: 'Sharp mechanics, calm design, clever loops.', gameCount: 7 },
  { id: 'c4', name: 'Horror', slug: 'horror', description: 'Tension-heavy, eerie, and atmospheric games.', gameCount: 6 },
  { id: 'c5', name: 'Racing', slug: 'racing', description: 'Arcade speed, realistic lines, and drift culture.', gameCount: 4 },
  { id: 'c6', name: 'Indie', slug: 'indie', description: 'Curated independent titles worth discovering.', gameCount: 16 },
  { id: 'c7', name: 'Multiplayer', slug: 'multiplayer', description: 'Competitive, co-op, and party-friendly games.', gameCount: 8 },
  { id: 'c8', name: 'Browser Games', slug: 'browser-games', description: 'Instant-play games with zero install friction.', gameCount: 5 },
  { id: 'c9', name: 'Android', slug: 'android', description: 'Official mobile-first Android game destinations.', gameCount: 4 },
  { id: 'c10', name: 'iPhone / iPad', slug: 'iphone-ipad', description: 'Trusted discovery for iPhone and iPad titles.', gameCount: 4 },
  { id: 'c11', name: 'PC', slug: 'pc', description: 'Desktop-first releases, downloads, and storefront pages.', gameCount: 16 },
  { id: 'c12', name: 'Mac', slug: 'mac', description: 'Mac-compatible games and official pages.', gameCount: 8 },
  { id: 'c13', name: 'Strategy', slug: 'strategy', description: 'Plan smarter, optimize systems, outthink opponents.', gameCount: 5 },
  { id: 'c14', name: 'Simulation', slug: 'simulation', description: 'Builders, sandboxes, and management loops.', gameCount: 5 },
  { id: 'c15', name: 'Story Rich', slug: 'story-rich', description: 'Narrative-first games with a strong emotional pull.', gameCount: 8 },
  { id: 'c16', name: 'Low Spec', slug: 'low-spec', description: 'Great games that run well on modest hardware.', gameCount: 10 },
  { id: 'c17', name: 'Free to Play', slug: 'free-to-play', description: 'Zero-cost starts and free official destinations.', gameCount: 9 },
  { id: 'c18', name: 'Co-op', slug: 'co-op', description: 'Shared progression, teamwork, and couch vibes.', gameCount: 6 },
  { id: 'c19', name: 'Roguelike', slug: 'roguelike', description: 'Repeatable runs, procedural variation, tight risk-reward.', gameCount: 5 },
  { id: 'c20', name: 'Survival', slug: 'survival', description: 'Resource pressure, crafting, and danger management.', gameCount: 5 }
];

const makeGame = (index: number, data: Partial<Game> & Pick<Game, 'title' | 'slug' | 'shortDescription' | 'longDescription' | 'developer' | 'publisher' | 'releaseDate' | 'priceType' | 'releaseType' | 'officialBadge' | 'featured' | 'trending' | 'newArrival' | 'popularity' | 'categories' | 'tags' | 'platforms' | 'links' | 'seoTitle' | 'seoDescription'>): Game => ({
  id: `g${index}`,
  coverImage: image(`${data.title} Cover`),
  bannerImage: image(`${data.title} Banner`, 'banner'),
  galleryImages: [
    image(`${data.title} Shot 1`, 'gallery'),
    image(`${data.title} Shot 2`, 'gallery'),
    image(`${data.title} Shot 3`, 'gallery')
  ],
  faq: [
    { question: `Where can I get ${data.title}?`, answer: `${data.title} is listed here with official or authorized destinations only.` },
    { question: `Is ${data.title} free or paid?`, answer: `${data.title} is marked as ${data.priceType?.toLowerCase()} on this directory entry.` }
  ],
  systemRequirements: ['OS: Windows 10 or newer', 'Memory: 8 GB RAM', 'Storage: 4 GB available space'],
  ...data
});

export const games: Game[] = [
  makeGame(1, { title: 'Neon Drift Reboot', slug: 'neon-drift-reboot', shortDescription: 'Stylish arcade racing with synthwave tracks.', longDescription: 'A premium-feeling arcade racer built for quick sessions, clean UI, and high-speed mastery. This listing demonstrates a Steam-first destination with extra official links.', developer: 'Pulse Arcade', publisher: 'Pulse Arcade', releaseDate: '2025-11-14', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: true, trending: true, newArrival: false, popularity: 98, categories: ['racing', 'action', 'indie'], tags: ['Arcade', 'Controller', 'Drift'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/neon-drift-reboot' }, { label: 'Official Website', type: 'official', url: 'https://example.com/neon-drift-reboot' }, { label: 'Trailer', type: 'trailer', url: 'https://example.com/trailer/neon-drift-reboot' }], seoTitle: 'Neon Drift Reboot Official Links & Overview', seoDescription: 'Discover Neon Drift Reboot with official Steam and studio links, screenshots, tags, and related racing picks.' }),
  makeGame(2, { title: 'Whisper House', slug: 'whisper-house', shortDescription: 'Indie horror set inside a looping Victorian mansion.', longDescription: 'This sample title shows how a horror game detail page can balance trust, atmosphere, and multiple official destination links.', developer: 'Lantern Thread', publisher: 'Lantern Thread', releaseDate: '2026-02-09', priceType: 'Paid', releaseType: 'Multi-link', officialBadge: true, featured: true, trending: true, newArrival: true, popularity: 96, categories: ['horror', 'story-rich', 'indie'], tags: ['Atmospheric', 'Narrative', 'Singleplayer'], platforms: ['pc', 'mac', 'steam', 'itchio'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/whisper-house' }, { label: 'itch.io Page', type: 'itch', url: 'https://example.com/itch/whisper-house' }], seoTitle: 'Whisper House Official Store Pages', seoDescription: 'Browse Whisper House with official Steam and itch.io destinations, gallery, FAQ, and related horror games.' }),
  makeGame(3, { title: 'Byte Colony', slug: 'byte-colony', shortDescription: 'Low-spec colony sim with deep automation chains.', longDescription: 'A strategy and simulation hybrid designed to run on modest hardware. Ideal for showcasing tags, system requirements, and a GitHub release link.', developer: 'Orbit Linen', publisher: 'Orbit Linen', releaseDate: '2025-09-30', priceType: 'Free', releaseType: 'Official Download', officialBadge: true, featured: false, trending: true, newArrival: false, popularity: 90, categories: ['strategy', 'simulation', 'low-spec'], tags: ['Automation', 'Base Building', 'Pixel Art'], platforms: ['pc', 'mac', 'github'], links: [{ label: 'GitHub Release', type: 'github', url: 'https://example.com/github/byte-colony/releases' }, { label: 'Official Website', type: 'official', url: 'https://example.com/byte-colony' }], seoTitle: 'Byte Colony Download & Official Links', seoDescription: 'Explore Byte Colony, a low-spec colony sim with GitHub releases, screenshots, platform badges, and official links.' }),
  makeGame(4, { title: 'Cloudblade Arena', slug: 'cloudblade-arena', shortDescription: 'Team-based action brawler for fast multiplayer matches.', longDescription: 'A multiplayer action sample entry designed to spotlight official website destinations and platform filters.', developer: 'Skystack', publisher: 'Skystack', releaseDate: '2026-01-21', priceType: 'Free', releaseType: 'Store Page', officialBadge: true, featured: true, trending: true, newArrival: true, popularity: 93, categories: ['action', 'multiplayer', 'free-to-play'], tags: ['PvP', 'Squads', 'Live Service'], platforms: ['pc', 'steam'], links: [{ label: 'Official Website', type: 'official', url: 'https://example.com/cloudblade-arena' }, { label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/cloudblade-arena' }], seoTitle: 'Cloudblade Arena Official Game Links', seoDescription: 'Find Cloudblade Arena official links, multiplayer details, and discovery tags on this curated directory page.' }),
  makeGame(5, { title: 'Pocket Quest Go', slug: 'pocket-quest-go', shortDescription: 'Mobile creature adventure built for fast daily sessions.', longDescription: 'A sample mobile-forward entry showing Play Store and App Store links side by side for cross-platform discovery.', developer: 'Tiny Beacon', publisher: 'Tiny Beacon', releaseDate: '2025-08-20', priceType: 'Free', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 84, categories: ['adventure', 'android', 'free-to-play'], tags: ['Mobile', 'Collecting', 'Daily Play'], platforms: ['android', 'ios'], links: [{ label: 'Play Store', type: 'playstore', url: 'https://example.com/play/pocket-quest-go' }, { label: 'App Store', type: 'appstore', url: 'https://example.com/app/pocket-quest-go' }], seoTitle: 'Pocket Quest Go App Links', seoDescription: 'Browse Pocket Quest Go with official Play Store and App Store links, game summary, and related mobile picks.' }),
  makeGame(6, { title: 'Signal Maze', slug: 'signal-maze', shortDescription: 'Minimal puzzle game about routing transmissions.', longDescription: 'A clean puzzle sample built for browser and mobile audiences with fast-play positioning.', developer: 'North Metric', publisher: 'North Metric', releaseDate: '2026-03-01', priceType: 'Free', releaseType: 'Browser Playable', officialBadge: true, featured: false, trending: false, newArrival: true, popularity: 79, categories: ['puzzle', 'browser-games', 'free-to-play'], tags: ['Logic', 'Minimal', 'Short Sessions'], platforms: ['browser', 'android'], links: [{ label: 'Play Now', type: 'browser', url: 'https://example.com/play/signal-maze' }, { label: 'Play Store', type: 'playstore', url: 'https://example.com/playstore/signal-maze' }], seoTitle: 'Signal Maze Browser Game', seoDescription: 'Play Signal Maze through its official browser page or mobile link with tags, screenshots, and category details.' }),
  makeGame(7, { title: 'Paper Dungeons', slug: 'paper-dungeons', shortDescription: 'Co-op roguelike with hand-drawn dungeons.', longDescription: 'This sample demonstrates how co-op, roguelike, and indie categories stack inside one card and one detail page.', developer: 'Folded Torch', publisher: 'Folded Torch', releaseDate: '2025-10-05', priceType: 'Paid', releaseType: 'Multi-link', officialBadge: true, featured: true, trending: false, newArrival: false, popularity: 88, categories: ['co-op', 'roguelike', 'indie'], tags: ['Runs', 'Loot', 'Online Co-op'], platforms: ['pc', 'steam', 'itchio'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/paper-dungeons' }, { label: 'itch.io Page', type: 'itch', url: 'https://example.com/itch/paper-dungeons' }], seoTitle: 'Paper Dungeons Official Links', seoDescription: 'Discover Paper Dungeons official store destinations and compare related roguelike co-op games.' }),
  makeGame(8, { title: 'Afterglow Farm', slug: 'afterglow-farm', shortDescription: 'Relaxed pixel farming sim with co-op seasons.', longDescription: 'A cozy simulation showcase with strong card visuals, legal-safe outbound links, and related-game discovery.', developer: 'Soft Acre', publisher: 'Soft Acre', releaseDate: '2025-07-12', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: true, newArrival: false, popularity: 91, categories: ['simulation', 'co-op', 'indie'], tags: ['Cozy', 'Farming', 'Pixel Art'], platforms: ['pc', 'mac', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/afterglow-farm' }, { label: 'Official Website', type: 'official', url: 'https://example.com/afterglow-farm' }], seoTitle: 'Afterglow Farm Steam & Official Links', seoDescription: 'Explore Afterglow Farm with platform badges, screenshots, and trusted official destinations only.' }),
  makeGame(9, { title: 'Hollow Transit', slug: 'hollow-transit', shortDescription: 'Story-rich sci-fi journey across a failing rail system.', longDescription: 'A narrative-forward adventure sample with a polished presentation and FAQ block ready for search indexing.', developer: 'Terminal Bloom', publisher: 'Terminal Bloom', releaseDate: '2026-02-24', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: true, trending: true, newArrival: true, popularity: 95, categories: ['story-rich', 'adventure', 'indie'], tags: ['Sci-Fi', 'Choices', 'Narrative'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/hollow-transit' }], seoTitle: 'Hollow Transit Official Overview', seoDescription: 'Browse Hollow Transit official game information, screenshots, FAQ, and related story-rich picks.' }),
  makeGame(10, { title: 'Dustline Survival', slug: 'dustline-survival', shortDescription: 'Open-zone survival crafting in a sunburned wasteland.', longDescription: 'A survival sample that pairs browser-safe legal messaging with system requirements and multi-link support.', developer: 'Red Mesa', publisher: 'Red Mesa', releaseDate: '2025-12-18', priceType: 'Paid', releaseType: 'Official Download', officialBadge: true, featured: false, trending: true, newArrival: false, popularity: 87, categories: ['survival', 'action', 'simulation'], tags: ['Crafting', 'Open Zone', 'Solo'], platforms: ['pc'], links: [{ label: 'Official Website', type: 'official', url: 'https://example.com/dustline-survival' }, { label: 'Official Download', type: 'download', url: 'https://example.com/downloads/dustline-survival' }], seoTitle: 'Dustline Survival Official Download', seoDescription: 'Visit Dustline Survival official pages and licensed download destinations with trust-first messaging.' }),
  makeGame(11, { title: 'Tiny Tactics Legends', slug: 'tiny-tactics-legends', shortDescription: 'Portable strategy battles for Android and iPhone.', longDescription: 'Mobile strategy sample with dual storefront links, tags, and trust-focused external-link cues.', developer: 'Signal Mint', publisher: 'Signal Mint', releaseDate: '2025-06-10', priceType: 'Free', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 76, categories: ['strategy', 'android', 'free-to-play'], tags: ['Turn-Based', 'Mobile', 'PvE'], platforms: ['android', 'ios'], links: [{ label: 'Play Store', type: 'playstore', url: 'https://example.com/play/tiny-tactics-legends' }, { label: 'App Store', type: 'appstore', url: 'https://example.com/app/tiny-tactics-legends' }], seoTitle: 'Tiny Tactics Legends Mobile Links', seoDescription: 'Official mobile links and game summary for Tiny Tactics Legends on Android and iPhone.' }),
  makeGame(12, { title: 'Loopline Express', slug: 'loopline-express', shortDescription: 'One-button browser runner with polished progression.', longDescription: 'A lightweight browser example perfect for the Best Free Browser Games collection.', developer: 'Micro Pier', publisher: 'Micro Pier', releaseDate: '2026-01-03', priceType: 'Free', releaseType: 'Browser Playable', officialBadge: true, featured: true, trending: false, newArrival: true, popularity: 80, categories: ['browser-games', 'action', 'low-spec'], tags: ['Runner', 'Quick Play', 'High Score'], platforms: ['browser'], links: [{ label: 'Play Now', type: 'browser', url: 'https://example.com/play/loopline-express' }], seoTitle: 'Loopline Express Browser Play Link', seoDescription: 'Launch Loopline Express through its official browser page and discover related quick-play titles.' }),
  makeGame(13, { title: 'Frostlight Protocol', slug: 'frostlight-protocol', shortDescription: 'Tactical co-op shooter with structured runs.', longDescription: 'A sharper action-co-op sample for premium card layouts and filter combinations.', developer: 'Shiver Foundry', publisher: 'Shiver Foundry', releaseDate: '2025-11-29', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: true, newArrival: false, popularity: 89, categories: ['action', 'co-op', 'multiplayer'], tags: ['Shooter', 'Tactical', 'Squads'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/frostlight-protocol' }, { label: 'Trailer', type: 'trailer', url: 'https://example.com/video/frostlight-protocol' }], seoTitle: 'Frostlight Protocol Store Page', seoDescription: 'View Frostlight Protocol official store links, tactical tags, and curated related games.' }),
  makeGame(14, { title: 'Lantern Lake Stories', slug: 'lantern-lake-stories', shortDescription: 'Warm story adventure with multiple endings.', longDescription: 'Story-rich adventure sample built for long-form page layouts and visual trust blocks.', developer: 'Marble Kite', publisher: 'Marble Kite', releaseDate: '2025-05-15', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 82, categories: ['story-rich', 'adventure', 'indie'], tags: ['Choices', 'Atmospheric', 'Singleplayer'], platforms: ['pc', 'mac', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/lantern-lake-stories' }, { label: 'Official Website', type: 'official', url: 'https://example.com/lantern-lake-stories' }], seoTitle: 'Lantern Lake Stories Official Links', seoDescription: 'Read about Lantern Lake Stories, its official destinations, and related narrative games.' }),
  makeGame(15, { title: 'Vault Circuit', slug: 'vault-circuit', shortDescription: 'Precision roguelike action for low-spec machines.', longDescription: 'A compact but sharp low-spec roguelike designed to show category overlap and clean badges.', developer: 'Glyph Harbor', publisher: 'Glyph Harbor', releaseDate: '2025-09-18', priceType: 'Free', releaseType: 'Official Download', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 74, categories: ['roguelike', 'low-spec', 'free-to-play'], tags: ['Runs', 'Action', 'Pixel'], platforms: ['pc', 'github'], links: [{ label: 'GitHub Release', type: 'github', url: 'https://example.com/github/vault-circuit/releases' }, { label: 'Official Website', type: 'official', url: 'https://example.com/vault-circuit' }], seoTitle: 'Vault Circuit Download Links', seoDescription: 'Find Vault Circuit official downloads and related free low-spec roguelikes.' }),
  makeGame(16, { title: 'Midnight Merge Hotel', slug: 'midnight-merge-hotel', shortDescription: 'Mobile puzzle mystery with elegant progression.', longDescription: 'A polished mobile puzzle sample with storefront support and SEO-friendly Q&A sections.', developer: 'Velvet Turn', publisher: 'Velvet Turn', releaseDate: '2026-02-14', priceType: 'Free', releaseType: 'Store Page', officialBadge: true, featured: false, trending: true, newArrival: true, popularity: 85, categories: ['puzzle', 'story-rich', 'android'], tags: ['Merge', 'Mystery', 'Mobile'], platforms: ['android', 'ios'], links: [{ label: 'Play Store', type: 'playstore', url: 'https://example.com/play/midnight-merge-hotel' }, { label: 'App Store', type: 'appstore', url: 'https://example.com/app/midnight-merge-hotel' }], seoTitle: 'Midnight Merge Hotel Official App Links', seoDescription: 'Official app links, screenshots, and puzzle mystery details for Midnight Merge Hotel.' }),
  makeGame(17, { title: 'OpenKart Workshop', slug: 'openkart-workshop', shortDescription: 'Open-source kart racer with modding support.', longDescription: 'An example of a GitHub-forward game entry that still feels premium and commercially trustworthy.', developer: 'OpenKart Collective', publisher: 'OpenKart Collective', releaseDate: '2025-04-28', priceType: 'Free', releaseType: 'Official Download', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 72, categories: ['racing', 'low-spec', 'indie'], tags: ['Open Source', 'Mods', 'Kart'], platforms: ['pc', 'mac', 'github'], links: [{ label: 'GitHub Release', type: 'github', url: 'https://example.com/github/openkart-workshop/releases' }, { label: 'Official Website', type: 'official', url: 'https://example.com/openkart-workshop' }], seoTitle: 'OpenKart Workshop Downloads', seoDescription: 'Browse OpenKart Workshop and reach its official GitHub releases and project website.' }),
  makeGame(18, { title: 'Temple of Tiles', slug: 'temple-of-tiles', shortDescription: 'Browser puzzle roguelike with daily challenges.', longDescription: 'A browser-playable puzzle sample for curated free collections and sticky filter layouts.', developer: 'Quiet Crate', publisher: 'Quiet Crate', releaseDate: '2026-03-12', priceType: 'Free', releaseType: 'Browser Playable', officialBadge: true, featured: true, trending: true, newArrival: true, popularity: 92, categories: ['browser-games', 'puzzle', 'roguelike'], tags: ['Daily Challenge', 'Browser', 'Grid'], platforms: ['browser'], links: [{ label: 'Play Now', type: 'browser', url: 'https://example.com/play/temple-of-tiles' }, { label: 'Trailer', type: 'trailer', url: 'https://example.com/video/temple-of-tiles' }], seoTitle: 'Temple of Tiles Play Now', seoDescription: 'Play Temple of Tiles through its official browser page and explore daily challenge puzzle picks.' }),
  makeGame(19, { title: 'Frontier Relay', slug: 'frontier-relay', shortDescription: 'Space survival management with hard resource choices.', longDescription: 'A survival-strategy hybrid that showcases deeper descriptions and related-game recommendations.', developer: 'Relay Forge', publisher: 'Relay Forge', releaseDate: '2025-10-24', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 83, categories: ['survival', 'strategy', 'simulation'], tags: ['Space', 'Resource Management', 'Singleplayer'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/frontier-relay' }], seoTitle: 'Frontier Relay Official Page', seoDescription: 'Official discovery page for Frontier Relay with platform tags, media, and trusted store destinations.' }),
  makeGame(20, { title: 'Chroma Brawl Party', slug: 'chroma-brawl-party', shortDescription: 'Color-chaos local multiplayer party game.', longDescription: 'A bright multiplayer sample perfect for curated collections and category-driven discovery.', developer: 'Party Mint', publisher: 'Party Mint', releaseDate: '2025-06-27', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: true, newArrival: false, popularity: 86, categories: ['multiplayer', 'action', 'indie'], tags: ['Party Game', 'Local Multiplayer', 'Controller'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/chroma-brawl-party' }], seoTitle: 'Chroma Brawl Party Store Link', seoDescription: 'Find the official Chroma Brawl Party store page and related multiplayer recommendations.' }),
  makeGame(21, { title: 'Quiet Harbor Detective', slug: 'quiet-harbor-detective', shortDescription: 'Slow-burn mystery adventure for story fans.', longDescription: 'A narrative detective sample designed for discovery through story-rich category pages.', developer: 'Harbor Note', publisher: 'Harbor Note', releaseDate: '2026-01-09', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: true, popularity: 81, categories: ['story-rich', 'adventure', 'puzzle'], tags: ['Mystery', 'Dialogue', 'Detective'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/quiet-harbor-detective' }, { label: 'Official Website', type: 'official', url: 'https://example.com/quiet-harbor-detective' }], seoTitle: 'Quiet Harbor Detective Official Links', seoDescription: 'Official links and overview for Quiet Harbor Detective, a story-rich mystery adventure.' }),
  makeGame(22, { title: 'Solar Siege Tactics', slug: 'solar-siege-tactics', shortDescription: 'Turn-based strategy battles with solar-powered mech squads.', longDescription: 'An indie strategy sample that rounds out the tactical browsing experience.', developer: 'Glass Atlas', publisher: 'Glass Atlas', releaseDate: '2025-08-08', priceType: 'Paid', releaseType: 'Store Page', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 78, categories: ['strategy', 'indie', 'story-rich'], tags: ['Turn-Based', 'Mechs', 'Campaign'], platforms: ['pc', 'steam'], links: [{ label: 'Steam Page', type: 'steam', url: 'https://example.com/steam/solar-siege-tactics' }], seoTitle: 'Solar Siege Tactics Official Store', seoDescription: 'Official store link and key details for Solar Siege Tactics, a tactical indie campaign game.' }),
  makeGame(23, { title: 'Noodle Ninja Mobile', slug: 'noodle-ninja-mobile', shortDescription: 'Fast swipe action game with snack-themed chaos.', longDescription: 'A playful mobile action sample for app-store filters and new arrivals modules.', developer: 'Snackbit', publisher: 'Snackbit', releaseDate: '2026-03-19', priceType: 'Free', releaseType: 'Store Page', officialBadge: true, featured: false, trending: true, newArrival: true, popularity: 88, categories: ['action', 'android', 'free-to-play'], tags: ['Mobile', 'Arcade', 'Swipe'], platforms: ['android', 'ios'], links: [{ label: 'Play Store', type: 'playstore', url: 'https://example.com/play/noodle-ninja-mobile' }, { label: 'App Store', type: 'appstore', url: 'https://example.com/app/noodle-ninja-mobile' }], seoTitle: 'Noodle Ninja Mobile App Links', seoDescription: 'Official app links and fast-view details for Noodle Ninja Mobile.' }),
  makeGame(24, { title: 'Castle Click Chronicle', slug: 'castle-click-chronicle', shortDescription: 'Idle browser kingdom builder with smart upgrades.', longDescription: 'A free browser/low-spec sample ideal for quick discovery and future monetization-ready collection pages.', developer: 'Clocktower Soft', publisher: 'Clocktower Soft', releaseDate: '2025-12-01', priceType: 'Free', releaseType: 'Browser Playable', officialBadge: true, featured: false, trending: false, newArrival: false, popularity: 75, categories: ['browser-games', 'strategy', 'low-spec'], tags: ['Idle', 'Kingdom Builder', 'Browser'], platforms: ['browser'], links: [{ label: 'Play Now', type: 'browser', url: 'https://example.com/play/castle-click-chronicle' }, { label: 'Official Website', type: 'official', url: 'https://example.com/castle-click-chronicle' }], seoTitle: 'Castle Click Chronicle Browser Link', seoDescription: 'Play Castle Click Chronicle on its official browser page with trusted outbound links only.' })
];

export const collections: Collection[] = [
  { id: 'fc1', title: 'Best Free Browser Games', slug: 'best-free-browser-games', description: 'Zero-install picks with instant play and polished design.', gameSlugs: ['signal-maze', 'loopline-express', 'temple-of-tiles', 'castle-click-chronicle'] },
  { id: 'fc2', title: 'Indie Horror Picks', slug: 'indie-horror-picks', description: 'Atmospheric, eerie, and carefully curated indie horror games.', gameSlugs: ['whisper-house'] },
  { id: 'fc3', title: 'Low-Spec Favorites', slug: 'low-spec-favorites', description: 'High-quality games that still run well on modest setups.', gameSlugs: ['byte-colony', 'loopline-express', 'vault-circuit', 'openkart-workshop'] }
];
